### ISSUE TITLE
[Feature request] Colored bubbles option

### ISSUE THREAD

**Issue by elynja** [SchildiChat/schildichat-android-next#10]
As this is possible in SchildiChat but not in Element, you might already be working on it. If not, it would be really nice if we could get at least some of the theming options we had in Schildichat, especially coloring the message bubbles, in SchildiNext too.

**Comment by SpiritCroc** [comment]
Indeed, I have a half-working implementation of such feature lying around somewhere since some time. So good idea from you to show some user interest, so I don't forget to finish that, since I personally don't actually need it xD

Actually, this time I was going for a full-blown color picker, since the new codbase makes it much easier to handle arbitrarily chosen user colors. I *just* need to make it somehow easier for users to select sensible colors, and to properly make it work for light and dark themes equally.

Maybe we should collect here what colors users are interested in changing :thinking: 
What I'm thinking of right now would be
- incoming message bubble background
- outgoing message bubble background
- chat background

**Comment by minihub19** [comment]
Just got the schildi next app... just wanted to say a big thank you for the work you put in to make such a nice and functional chat app vs... even the main app - Element! This is SO much more pleasant to use... 

I am definitely excited about the coloured bubbles. I find them really useful in enhancing readability because sometimes it is confusing to differentiate where my message ends and the message starts from whoever I am responding too... so many designs have everything all coloured in grey... it really makes things difficult for me... I agree with what was mentioned in this: https://github.com/element-hq/element-x-android/issues/1094

I find what fluffychat does with their theme is pleasant... BUT I do not like that a lot of the themes are pale and pastel colours... the lack of contrast between the chat bubbles makes it hard to read. Their green theme is nice though! It has high contrast between the two different tints and tones of green. I don't mind the traditional blue bubble with grey. But would like theme options where there are tints and tones of the same colour used.

https://www.android.com/google-messages/
The sliding indicator on the animation looks like a good idea to people to pick themes but not go too crazy.

I like deeper colours for chat for example
Red https://www.colorhexa.com/d10000
Green https://www.colorhexa.com/43dc24
Blue https://www.colorhexa.com/005be7
Purple https://www.colorhexa.com/5438ce
A cafe combo would be fun...
https://www.colorhexa.com/4b3621 and https://www.colorhexa.com/a67b5b

I hope that helps you and I look forward to seeing the change.

**Comment by SpiritCroc** [comment]
> Just got the schildi next app... just wanted to say a big thank you for the work you put in to make such a nice and functional chat app vs... even the main app - Element! This is SO much more pleasant to use...

Great to hear! :)

> I like deeper colours for chat for example

I'm not planning to add any specific colors this time, just a color picker which allows you to chose any color you want yourself. :wink:
