### ISSUE TITLE
Publish on F-Droid (main repository)

### ISSUE THREAD

**Issue by austinhuang0131** [SchildiChat/schildichat-android-next#18]
Since [Element X is now there](https://f-droid.org/en/packages/io.element.android.x/), though I'm not sure whether you forking components constitute a blocker.

**Comment by SpiritCroc** [comment]
Indeed, the main reason why I haven't PRed SchildiNext to fdroid yet are our forks of the Rust libraries (matrix sdk and rich-text-editor), irrespective of whether EleX is on fdroid or not.

In more detail, I haven't had enough motivation to publish these libraries to sonatype/mavencentral since I don't have experience with this yet and it seems like a lot of paperwork. Sonatype seems the best library hosting solution though, considering jitpack doesn't support building Rust libraries afaik.

Currently, I host these libraries on GitHub packages. Unfortunately GitHub requires you to use an API key to retrieve packages, even for public repositories. By now github is apparently [no longer interested in opening this up](https://github.com/orgs/community/discussions/26634#discussioncomment-8527086). Now, when it comes to the fdroid main repository, requiring any secrets not available in the public repo for building is a no-go. (Also if we'd hard-code some github API keys in the repo for some throwaway account, github will immediately detect and block, so that won't work either xD).

So I probably need to get through the sonatype application process at some point.

**Comment by linsui** [comment]
Can't we build those libs? :)

**Comment by SpiritCroc** [comment]
@linsui I don't know about what means the fdroid tools provide for building these libs, but it's totally possible to build these dependencies locally!
- [rich-text-editor](https://github.com/SchildiChat/matrix-rich-text-editor) can be released to local maven via `./gradlew publishToMavenLocal`, such that when you add `mavenLocal()` to SchildiChat's `settings.gradle.kts` it can be picked up from there.
- The Rust SDK is a bit more complicated, you need both the [actual SDK](https://github.com/SchildiChat/matrix-rust-sdk) and the [bindings](https://github.com/SchildiChat/matrix-rust-components-kotlin). With these you can run some script will output an `.aar` into the SchildiChat directory, which the build process will automatically pick up if stored at the correct place. The repos have some READMEs for that but you can also check `./sc_tools/rust_sdk_build.sh` in the SchildiChat repo, which I usually call. If one wants to build for a certain architecture separately rather then all at once, that's possible with `./sc_tools/rust_sdk_build.sh -t aarch64-linux-android`. So if the fdroid build process doesn't allow you to re-use libraries for split ABI then that would speed things up, otherwise probably better to just build the SDK once.

Of course one needs to have a working Rust compiler set up in addition to the common Android build tools, and maybe some more dependencies, I'd need to check the respective READMEs again.

I'm just realizing that picking up the correct revision for the rust-sdk is a bit trickier than just following a single git tag, since the upstream build scripts that I adopted only add a git tag to the rust-components but not the SDK. [How I've been doing it when merging upstream releases](https://github.com/SchildiChat/schildichat-android-next/blob/77b92cf203e7847802792a1bcc21e29f5ca8a082/sc_tools/rust_sdk_update.sh) is fetching it from github releases, which would also work for SchildiChat:
```
> rust_ver=0.2.22
> curl https://github.com/SchildiChat/matrix-rust-components-kotlin/releases/tag/sc-sdk-v"$rust_ver" | grep ">https://github.com/SchildiChat/matrix-rust-sdk/tree/" | sed "s|.*https://github.com/SchildiChat/matrix-rust-sdk/tree/\\(.*\\)</a>.*|\\1|g"
9be4a0ed8531a37555bdd1d014b7a38015ae9fb6
```

I assume I could also teach the upstream build scripts to just also add a git tag to the SDK repo itself, but for merge conflicts it's always good to limit the changes I do.

BTW, my desktop with decent hardware (AMD 5950X) building a release build of the Rust SDK for all architectures takes around 45 Minutes, so whatever runs the fdroid builds would need for allow such build times :)

**Comment by linsui** [comment]
We can do that, no problem. :)

**Comment by linsui** [comment]
Looks like these libs and the app use different rust, ndk and jdk. Can you use the same version for them?

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/commit/7240a31191a4545d35a9a91d847ddb3d8d67a455 Not reproducible.

**Comment by SpiritCroc** [comment]
Thank you for the update! I'll try to look into it when I get time (earliest next week?). Some questions and notes to the fdroiddata commit:

- I did not prepare for reproducible builds, what's the best way to check for things breaking reproducible builds? Things I assume are broken right now would be:
    -  I do a `git checkout -b sc_fdroid` in prebuild, which ends up in the apk as branch name, so the app knows which store it was installed from by checking the build branch - if we're going for reproducible builds I probably should omit that or the fdroid repo should do something similar, I'll need to think about that a bit more.
    - I assume I need to copy your `postbuild` steps for my recipe. 
    - I have a different maptiler API key, since Element discourages forks to use theirs. Also I haven't set the map IDs when building.
- `AutoName: Element X` sounds wrong, is that a copy-paste error or something I can fix in the code?
- `Translations` should probably point to our [weblate](https://weblate.spiritcroc.de/projects/schildichat/schildichat-android-next/) (though the upstream translation link is also applicable for upstream strings)

**Comment by linsui** [comment]
> what's the best way to check for things breaking reproducible builds

We need to pin the toolchain versions as many as possible first. Currently I applied some patches to build everything with the same toolchain (jdk 21, ndk r27b
, rust  1.82.0) so the build is not reproducible with yours. Can you also use the same toolchain for libs and app? It makes the build easier.

> I assume I need to copy your postbuild steps for my recipe.

This fixes a reproducible build issue of element x. I assume that schildichat-android-next has the same issue but I'm not sure yet.

> I have a different maptiler API key, since Element discourages forks to use theirs. Also I haven't set the map IDs when building.

Which key should I use?

> AutoName: Element X sounds wrong, is that a copy-paste error or something I can fix in the code?

I haven't check that part. I'll fix it.

> Translations should probably point to our [weblate](https://weblate.spiritcroc.de/projects/schildichat/schildichat-android-next/) (though the upstream translation link is also applicable for upstream strings)

Thanks, will fix it.

**Comment by SpiritCroc** [comment]
> We need to pin the toolchain versions as many as possible first. Currently I applied some patches to build everything with the same toolchain (jdk 21, ndk r27b , rust 1.82.0) so the build is not reproducible with yours. Can you also use the same toolchain for libs and app? It makes the build easier.

Makes sense, I'll have a look when I get to it. Usually I just follow upstream toolchain definitions where it is explicitly defined, but in this case it's probably ok to deviate and live with the added merge conflicts.

> Which key should I use?

I'm building right now with `xbrDyz47XLB1x53xbOOg`.

> Thanks, will fix it.

Thank you!

**Comment by linsui** [comment]
Let me update the metadata and see if there is any diff, thanks!

**Comment by linsui** [comment]
https://github.com/SchildiChat/matrix-rich-text-editor/blob/sc_v3.0.6/platforms/android/library/build.gradle#L93 This still uses ndk r27b. I guess it can't be updated along with other libs since it's not updated frequently?

**Comment by SpiritCroc** [comment]
Ah my bad, I guess I missed that one, I'll update it.

**Comment by SpiritCroc** [comment]
Bumped rich-text-editor for NDK r27c and pushed another fdroid release, v0.7.3.sc15. Hope I didn't miss any other place now

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/commit/84c1e059403e200843fc1a426672aa6367be2a28

> I do a git checkout -b sc_fdroid in prebuild, which ends up in the apk as branch name

I tried to match this with

```
sed -i -e 's/"git rev-parse --abbrev-ref HEAD"/"echo sc_fdroid"/' plugins/src/main/kotlin/extension/Utils.kt
```

but in your apk the branch name is HEAD. Is this correct?

The rust libs have some embeded path which can be removed with `--remap-path-prefix`. Can you add this to your buildscript?

Now only baseline.prof is not reproducible. This is tricky. This may be related to the cpu core number and differs in different build. Do you have any idea?

**Comment by SpiritCroc** [comment]
> https://gitlab.com/linsui/fdroiddata/-/commit/84c1e059403e200843fc1a426672aa6367be2a28
> 
> > I do a git checkout -b sc_fdroid in prebuild, which ends up in the apk as branch name
> 
> I tried to match this with
> 
> ```
> sed -i -e 's/"git rev-parse --abbrev-ref HEAD"/"echo sc_fdroid"/' plugins/src/main/kotlin/extension/Utils.kt
> ```
> 
> but in your apk the branch name is HEAD. Is this correct?

Ah yes, sorry, I removed the `git checkout` for my latest builds since I figured it didn't make sense to do if F-Droid would distribute the same apks anyway, so there's less we need to worry about. (I do build releases for my fdroid repos with `fdroidserver` as well, though not sandboxed/virtualized and with my OS'es toolchain.)

> The rust libs have some embeded path which can be removed with `--remap-path-prefix`. Can you add this to your buildscript?

ok, I will look into this for the next release!

> Now only baseline.prof is not reproducible. This is tricky. This may be related to the cpu core number and differs in different build. Do you have any idea?

Hm, I'm not really familiar with that unfortunately.

**Comment by linsui** [comment]
Do you use any different toolchains, e.g. newer AGP, vs element x? Element x doesn't have this problem so there must be something different.

**Comment by SpiritCroc** [comment]
I usually don't touch the AGP version to avoid merge-conflicts with upstream. I'm not sure what toolchain upstream exactly uses. Something that comes to my mind right now is that I've been using the JDK bundled with android-studio, at least I assume fdroidserver would use that JDK from my `JAVA_HOME` variable, I do have some other openjdks installed as well on my OS.  I could probably switch to the openjdk that I get from Arch instead, if that helps. :thinking: 

Re `--remap-path-prefix`, I think it requires an argument, is there one you would would recommend to align my builds with the fdroid-built ones?

**Comment by linsui** [comment]
Not sure if openjdk helps, we can have a try. :)

`--remap-path-prefix=$HOME/.cargo/=.cargo/` can remove the embeded cargo home path and `--remap-path-prefix=$(pwd)=.` can remove the embeded repo path. Not sure where you should add these flags though. I just use absolute path. Maybe you need to use rootProject path in gradle and $sdk_path in build.sh.

**Comment by linsui** [comment]
The baseline files can be disabled but that may affect the performance.

**Comment by SpiritCroc** [comment]
ok, thank you! I'll experiment with the Rust build and Java versions when I find some more time.
I'd rather not disable the baseline files completely, at least in my own repo I like to provide the best SchildiChat version there is.

**Comment by SpiritCroc** [comment]
I just released new versions for the two Rust libraries with `--remap-path-prefix` which I'll include in the next SchildiChat Next release. I furthermore compiled the current revision from the main branch with both the JetBrains JDK and openjdk 21, and from what I can tell the resulting `baseline.prof` files are identical, so I fear that won't help. :face_with_diagonal_mouth:

**Comment by linsui** [comment]
> I just released new versions for the two Rust libraries with --remap-path-prefix which I'll include in the next SchildiChat Next release.

Where do you add the arg? Do we need to also add that or it will be used by default somehow?

The baseline.prof seems to be related to the core number. How much cores do you use?

**Comment by SpiritCroc** [comment]
> Where do you add the arg? Do we need to also add that or it will be used by default somehow?

I set it in my build environment like this currently:
```
export RUSTFLAGS="--remap-path-prefix=$HOME/.cargo/=.cargo/ --remap-path-prefix=$(realpath "$SDK_DIR")/=."
```

If the fdroid build environment doesn't have something comparable by default, I think the recipe will need to do something similar.

> The baseline.prof seems to be related to the core number. How much cores do you use?

I'm right now building on an AMD 5950x with 16 cores / 32 threads, and I have not consciously limited the cores that the build uses. Do you know if it's possible to control the cores used for `baseline.prof` without spinning up a VM?

**Comment by linsui** [comment]
OK, then I'll do the same when building those libs. I'll also try building it with 16 cores. We set the core numbers with

```
      - export CPUS_MAX=16
      - export CPUS=$(getconf _NPROCESSORS_ONLN)
      - for (( c=$CPUS_MAX; c<$CPUS; c++ )) ; do echo 0 > /sys/devices/system/cpu/cpu$c/online
        ; done
```

**Comment by SpiritCroc** [comment]
Not sure if we'd need 32 instead, since that's what the OS sees due to the hyper-threading :thinking:

**Comment by SpiritCroc** [comment]
`sc_v0.7.4.sc16` with the updated Rust libs is up.

**Comment by linsui** [comment]
It builds reproducibly now. Not sure if it will still be reproducible on the buildserver. :shrug:

**Comment by SpiritCroc** [comment]
Nice! Let's hope the best :crossed_fingers: 
Thank you for your help!

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16989

**Comment by SpiritCroc** [comment]
@linsui if I see correctly, right now the ARM-32 build succeeded but arm64 and x86 are failing with a baseline.prof diff. I'll probably do a bugfix release soon so wanted to check if there's some quick thing I could include to help bringing up a full fdroid release.

- Can the fdroid buildserver use 32 cores instead of 16? Since 32 is what my OS sees for my CPU
- Do you happen to know if I can somehow limit gradle (?) on my end to 16 cores? (Would be nice if I didn't have to disable cores globally, but only for my fdroidserver builds)
- I guess for now I can also limit my CPU cores globally like in the recipe while building fdroid releases, which isn't great but could be a temporary workaround to get things going
- Or maybe 16 cores is correct but the buildserver didn't get them for all builds anyway? :thinking:

**Comment by linsui** [comment]
We only have 23 cores... We'll let it retry. Maybe it will be reproducible in the next cycle. I don't know how to limit the cores for gradle only. And @licaon-Kter tested it locally and the apk is always reproducible. :shrug:

**Comment by mpeter50** [comment]
Could it help if you used [taskset](https://man.archlinux.org/man/taskset.1) to change the CPU affinity of the process that starts the build process? Not sure if child processes inherit it though, man pages dont mention it happening.

**Comment by linsui** [comment]
The failed abis are reproducible in this cycle.

**Comment by licaon-kter** [comment]
@spiritcroc maybe I've missed the post, what's the future plan about Next vs Old?

Eg. ElementX is said to replace the old codebase of Element sometime in the future, so users don't need to install a new app... but we lose reproducibility.

**Comment by SpiritCroc** [comment]
@licaon-kter initially I planned to follow whatever Element is doing. I'm not sure if Element is still attached to the approach with re-using the package name and shipping EleX as an update, I have the feeling their statements became more vague over time when users asked them about this. Anyway if there's a good reason to deviate from EleX, I'm happy to do so, i.e. by keeping the packages separate anyway and just add a notification to the old app that switching is recommended. Maybe also add a nice account migration if I have time and motivation. Reasons for that approach I can think of right now are:

- Reproducible builds are quite nice to have
- Element tends to overestimate how suitable (or "ready") their new clients are for users, compared to the feature-rich old clients. So I don't really want to force users to use the new app if they don't want to (or maybe even are not able to, there's still homeservers that don't allow sliding sync).
- The old app has fdroid and gplay variants like Element, Next only uses one (always building fdroid flavor and just using unifiedpush's FCM lib rather then the proprietary Google one), which leaves us with unnecessary duplication when upgrading
- I prefer the new package name, actually reflecting the app's name (the old package name was done before deciding on an app name)

That's quite a few reasons to stay with separate packages now that I think of it, so if you ask me right now, that's what I currently favor. But eventually I'll want to defer the final decision to when Element does the switch.

FWIW, *if* Element is going to do the switch anytime soon, then I'll very likely stay with separate packages for at least a while longer, as I don't agree with Element's narrative that EleX is already the client that "everyone should use".
