### ISSUE TITLE
Membership events mark a room as unread (green dot)

### ISSUE THREAD

**Issue by BurnyBoi** [SchildiChat/schildichat-android-next#44]
**Describe the bug**
Whenever any membership event (e.g. display name change, join, leave) occurs in a room, the room is marked as unread with a green dot.

**To Reproduce**
- read a room, so that it is new marked unread
- go away for a while
- observe green dotted rooms and check them out
- in many cases all that happened was a display name change or a joined user.

**Expected behavior**
Rooms should only be marked unread for messages. Green dots on the room list should be reserved for messages more important than the regular unreads w/ gray dots, such as mentions or unreads in rooms set to Noisy.

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Graphene OS, Android 15.

**Additional context**
 - App version: 0.7.5 sc18 (9420)
 - Store: SpiritCroc's F-Droid
 - Homeserver: matrix.org
 - Related experimental/labs settings: "SC overview layout" enabled. Behavior still occurs with it disabled though.
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: no

**Upstream relevance**
 - Does this issue exist in Element X Android? Yes
 - If this issue exists in Element X Android, please also link the corresponding bug report
 https://github.com/element-hq/element-x-android/issues/3543

**Additional context**
number one most annoying UX bug in Element X/Schildichat Next. Severely reduces the reliability of unread markers. Whenever a room has the green unread marker I have to assume nothing actually has happened and only watch for the gray unread markers.

**Comment by SpiritCroc** [comment]
I can not reproduce this. I heard some users have this issue because of another Matrix client having messed up their account-specific push rules, so it's worth checking those.

I'm not sure what the best way to check push rules as a user is nowadays. Once it was accessible in element-web/desktop but I currently do not find it anymore. In the old SchildiChat/Element Android apps it's possible to at least view push rules in via Settings / Advanced Settings / Push rules, one could at least check if that's the issue by looking out for suspicious rules matching `m.room.member`. But not sure how one would change that now that I don't find it on desktop anymore.

Also worth checking on Next, when you navigate to the "Notifications" settings, if it complains about unsupported custom push rules. If it does, clicking the button to clear those could help.

**Comment by BurnyBoi** [comment]
I think I was able to fix this. I'm not sure which of these fixed it but I did the following:

- Using Hydrogen Web, I logged in, enabled push notifications, then disabled them
- On latest Element Web, I used "Reset to default settings" under the notification settings, then picked my desired settings again
